version: "3.9"

services:
  notes-db:
    image: postgres:latest
    container_name: notes-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notes-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"   # host:container
    # scripts DDL + seeds
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"
